steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/mansion-watch-scraper",
        "-f",
        "mansion_watch_scraper/pubsub/Dockerfile",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mansion-watch-scraper"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mansion-watch-scraper"
      - "--image"
      - "gcr.io/$PROJECT_ID/mansion-watch-scraper"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--no-allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "1"
      - "--service-account"
      - "cloud-run-pubsub-invoker@${PROJECT_ID}.iam.gserviceaccount.com"
      - "--set-env-vars"
      - "ENV=production,MONGO_URI=${_MONGO_URI},GCP_PROJECT_ID=${_GCP_PROJECT_ID},PUBSUB_TOPIC=${_PUBSUB_TOPIC},PUBSUB_SUBSCRIPTION=${_PUBSUB_SUBSCRIPTION}"
      - "--set-secrets"
      - "service-account.json=mansion-watch-service-account:latest"

  # Grant the Pub/Sub service account permission to invoke the service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "add-iam-policy-binding"
      - "mansion-watch-scraper"
      - "--region"
      - "asia-northeast1"
      - "--member"
      - "serviceAccount:cloud-run-pubsub-invoker@${PROJECT_ID}.iam.gserviceaccount.com"
      - "--role"
      - "roles/run.invoker"

substitutions:
  _MONGO_URI: mongodb+srv://mansionwatch:mansiondaisuki@mansionwatch.mbt6a.mongodb.net/?retryWrites=true&w=majority&appName=MansionWatch
  _GCP_PROJECT_ID: daring-night-451212-a8
  _PUBSUB_TOPIC: mansion-watch-scraper-topic
  _PUBSUB_SUBSCRIPTION: mansion-watch-scraper-sub-push

images:
  - "gcr.io/$PROJECT_ID/mansion-watch-scraper"
